version: '3.8'

services:
  frontend:
    build:
      context: ./infra
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./infra
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlserver://<username>:<password>@db:1433;database=<dbname>
      - JWT_SECRET=<your_jwt_secret>
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=<YourStrong@Passw0rd>
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data: