apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-onboarding-backend
  labels:
    app: user-onboarding
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-onboarding
  template:
    metadata:
      labels:
        app: user-onboarding
    spec:
      containers:
        - name: backend
          image: user-onboarding-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_secret
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: regcred