apiVersion: v1
kind: Service
metadata:
  name: user-onboarding-service
  labels:
    app: user-onboarding
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: user-onboarding